filebeat.config.modules:
  enabled: true
  path: /etc/filebeat/modules.d/*.yml

filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/messages
  exclude_files: ["auth.log*"]
  exclude_files: [".gz$"]
  multiline:
  pattern: "^\\s"
  match: after
  tags: ["syslog"]

- type: log
  enabled: true
  paths:
    - /var/log/auth.log
  exclude_files: [".gz$"]
  multiline:
  pattern: "^\\s"
  match: after
  tags: ["auth"]

# apache, nginx, lighttpd logpath
- type: log
  enabled: true
  paths:
  - /var/log/apache/*error.log
  tags: ["apache-error-log"]

# php-fpm logpath
- type: log
  enabled: true
  paths:
  - /var/log/php5-fpm.log
  tags: ["php-fpm-log"]

output.logstash:
  hosts: ["10.60.0.140:5044"]
  files:
    path: /var/log/filebeat
    name:
    keepfiles: 7
    rotateeverybytes: 10485760 # 10 MB

setup.kibana:
  host: "10.60.0.140:5601"
